# Site settings
title: Participatory Approaches to Machine Learning
description: > # this means to ignore newlines until "baseurl:"
    Participatory Approaches to Machine Learning
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]

sass:
    style: compressed
